const MODELS = ['users'];

const STATUS_CODES = {
    OK: 200,
    CREATED: 201,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    PERMISSION_DENIED: 403,
    NOT_FOUND: 404,
    SERVER_ERROR: 500
}

export { MODELS, STATUS_CODES };